# permissions for end users to edit expressapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: express-operator
    app.kubernetes.io/managed-by: kustomize
  name: expressapp-editor-role
rules:
- apiGroups:
  - web.kurosawa.dev
  resources:
  - expressapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.kurosawa.dev
  resources:
  - expressapps/status
  verbs:
  - get
