apiVersion: web.kurosawa.dev/v1alpha1
kind: ExpressApp
metadata:
  name: sample-api
  namespace: default
spec:
  image: 986154984217.dkr.ecr.ap-northeast-1.amazonaws.com/container-nodejs-api-8000:v1.0.4
  replicas: 1
  port: 8000
  metricsPath: /metrics